# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal
from . import discount_allocation


class AppliedDiscount(BaseModel):
  """A discount that was successfully applied."""

  model_config = ConfigDict(
    extra="allow",
  )
  code: str | None = None
  """
    The discount code. Omitted for automatic discounts.
    """
  title: str
  """
    Human-readable discount name (e.g., 'Summer Sale 20% Off').
    """
  amount: int = Field(..., ge=0)
  """
    Total discount amount in minor (cents) currency units.
    """
  automatic: bool | None = False
  """
    True if applied automatically by merchant rules (no code required).
    """
  method: Literal["each", "across"] | None = None
  """
    Allocation method. 'each' = applied independently per item. 'across' = split proportionally by value.
    """
  priority: int | None = Field(None, ge=1)
  """
    Stacking order for discount calculation. Lower numbers applied first (1 = first).
    """
  allocations: list[discount_allocation.DiscountAllocation] | None = None
  """
    Breakdown of where this discount was allocated. Sum of allocation amounts equals total amount.
    """
