# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Context(BaseModel):
  """Location and market context. All fields optional. Platforms MAY geo-detect from request; provided fields MUST override."""

  model_config = ConfigDict(
    extra="allow",
  )
  country: str | None = Field(None, pattern="^[A-Z]{2}$")
  """
    ISO 3166-1 alpha-2 country code (e.g., 'US', 'CA'). Market context for product availability, pricing, and currency. Detected from request if omitted.
    """
  region: str | None = None
  """
    State, province, emirate, or district (e.g., 'CA', 'ON', 'Dubai'). Format varies by country.
    """
  postal_code: str | None = None
  """
    Postal or ZIP code for regional refinement. Not applicable in all countries.
    """
