# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing import Any
from . import (
  media as media_1,
  price_range,
  product_option,
  rating as rating_1,
  variant,
)


class Description(BaseModel):
  """Product description in one or more formats. At least one format must be provided."""

  model_config = ConfigDict(
    extra="allow",
  )
  plain: str | None = None
  """
    Plain text description.
    """
  html: str | None = None
  """
    HTML-formatted description.
    """
  markdown: str | None = None
  """
    Markdown-formatted description.
    """


class Product(BaseModel):
  """A product in the catalog with variants and options."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Global ID (GID) uniquely identifying this product.
    """
  handle: str | None = None
  """
    URL-safe product handle/slug.
    """
  title: str
  """
    Product title.
    """
  description: Description
  """
    Product description in one or more formats. At least one format must be provided.
    """
  url: AnyUrl | None = None
  """
    Canonical product page URL.
    """
  category: str | None = None
  """
    Category: taxonomy path (e.g., 'Apparel > Shirts') or merchant-defined type (e.g., 'Premium Tee').
    """
  price: price_range.PriceRange
  """
    Price range across all variants.
    """
  list_price: price_range.PriceRange | None = None
  """
    List price range before discounts (for strikethrough display).
    """
  media: list[media_1.Media] | None = None
  """
    Product media (images, videos, 3D models). First item is the featured media for listings.
    """
  options: list[product_option.ProductOption] | None = None
  """
    Product options (Size, Color, etc.).
    """
  variants: list[variant.Variant] = Field(..., min_length=1)
  """
    Purchasable variants of this product. First item is the featured variant for listings.
    """
  rating: rating_1.Rating | None = None
  """
    Aggregate product rating.
    """
  tags: list[str] | None = None
  """
    Product tags for categorization and search.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the standard product model.
    """
