# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict
from . import (
  link,
  media as media_1,
  price as price_1,
  rating as rating_1,
  selected_option,
)
from typing import Any


class Description(BaseModel):
  """Variant description in one or more formats. At least one format must be provided."""

  model_config = ConfigDict(
    extra="allow",
  )
  plain: str | None = None
  """
    Plain text description.
    """
  html: str | None = None
  """
    HTML-formatted description.
    """
  markdown: str | None = None
  """
    Markdown-formatted description.
    """


class Availability(BaseModel):
  """Variant availability for purchase."""

  model_config = ConfigDict(
    extra="allow",
  )
  available: bool | None = None
  """
    Whether this variant can be purchased.
    """


class Seller(BaseModel):
  """Optional seller context for this variant."""

  model_config = ConfigDict(
    extra="allow",
  )
  name: str | None = None
  """
    Seller display name.
    """
  links: list[link.Link] | None = None
  """
    Seller policy and information links.
    """


class Variant(BaseModel):
  """A purchasable variant of a product with specific option selections."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Global ID (GID) uniquely identifying this variant. Used as item.id in checkout.
    """
  sku: str | None = None
  """
    Business-assigned identifier for inventory and fulfillment.
    """
  barcode: str | None = None
  """
    Industry-standard identifier (UPC, EAN, ISBN) for the variant.
    """
  handle: str | None = None
  """
    URL-safe variant handle/slug.
    """
  title: str
  """
    Variant display title (e.g., 'Blue / Large').
    """
  description: Description
  """
    Variant description in one or more formats. At least one format must be provided.
    """
  url: AnyUrl | None = None
  """
    Canonical variant page URL.
    """
  category: str | None = None
  """
    Category: taxonomy path (e.g., 'Apparel > Shirts') or merchant-defined type (e.g., 'Premium Tee').
    """
  price: price_1.Price
  """
    Current selling price.
    """
  list_price: price_1.Price | None = None
  """
    List price before discounts (for strikethrough display).
    """
  availability: Availability | None = None
  """
    Variant availability for purchase.
    """
  selected_options: list[selected_option.SelectedOption] | None = None
  """
    Option selections that define this variant.
    """
  media: list[media_1.Media] | None = None
  """
    Variant media (images, videos, 3D models). First item is the featured media for listings.
    """
  rating: rating_1.Rating | None = None
  """
    Variant rating.
    """
  tags: list[str] | None = None
  """
    Variant tags for categorization and search.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the standard variant model.
    """
  seller: Seller | None = None
  """
    Optional seller context for this variant.
    """
