# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class MenuModifierGroup(BaseModel):
  """Group of modifier options with selection constraints."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Modifier group identifier.
    """
  name: str
  """
    Display name for the modifier group.
    """
  minimum_selections: int | None = Field(None, ge=0)
  """
    Minimum number of selections required from this group.
    """
  maximum_selections: int | None = Field(None, ge=0)
  """
    Maximum number of selections allowed from this group.
    """
  max_per_modifier: int | None = Field(1, ge=0)
  """
    Maximum quantity allowed per modifier option. Defaults to 1 (each modifier can be selected at most once). Set value > 1 to allow per-modifier quantities.
    """
  modifier_options: list[MenuModifierOption] = Field(..., min_length=1)
  """
    Available modifier options within this group.
    """
  type: str | None = None
  """
    Modifier group type classification.
    """


class MenuModifierOption(BaseModel):
  """Selectable option within a modifier group."""

  model_config = ConfigDict(
    extra="allow",
  )
  item_id: str
  """
    Modifier item identifier for this option.
    """
  child_modifier_groups: list[MenuModifierGroup] | None = None
  """
    Nested modifier groups required after selecting this option.
    """


MenuModifierGroup.model_rebuild()
