# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import ConfigDict
from ...shopping.types.context import Context


class RestaurantContext(Context):
  """Location and market context for restaurant operations."""

  model_config = ConfigDict(
    extra="allow",
  )
  intent: str | None = None
  """
    Background context for semantic search (e.g., 'quick lunch nearby', 'family meal under $30').
    """
