# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import Field, RootModel
from ...shared.types import dropoff_location_req, pickup_location_req


class FulfillmentDestinationRequest(
  RootModel[
    dropoff_location_req.DropoffLocationRequest
    | pickup_location_req.PickupLocationRequest
  ]
):
  root: (
    dropoff_location_req.DropoffLocationRequest
    | pickup_location_req.PickupLocationRequest
  ) = Field(..., title="Fulfillment Destination Request")
  """
    A destination for pickup or on-demand delivery in restaurant checkout.
    """
