# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel
from ...shopping.types import retail_location_req
from ...delivery.types import delivery_inputs_req, quote_reference


class RestaurantFulfillmentMethodUpdateRequest1(BaseModel):
  """A fulfillment method for pickup or on-demand delivery in restaurant checkout."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique fulfillment method identifier.
    """
  destinations: list[retail_location_req.RetailLocationRequest] | None = None
  """
    Available pickup locations.
    """
  selected_destination_id: str | None = None
  """
    ID of the selected destination.
    """


class RestaurantFulfillmentMethodUpdateRequest2(BaseModel):
  """A fulfillment method for pickup or on-demand delivery in restaurant checkout."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique fulfillment method identifier.
    """
  delivery: (
    quote_reference.DeliveryQuoteReference
    | delivery_inputs_req.DeliveryInputsRequest
  )
  """
    Required delivery inputs for on-demand delivery.
    """


class RestaurantFulfillmentMethodUpdateRequest(
  RootModel[
    RestaurantFulfillmentMethodUpdateRequest1
    | RestaurantFulfillmentMethodUpdateRequest2
  ]
):
  root: (
    RestaurantFulfillmentMethodUpdateRequest1
    | RestaurantFulfillmentMethodUpdateRequest2
  ) = Field(..., title="Restaurant Fulfillment Method Update Request")
  """
    A fulfillment method for pickup or on-demand delivery in restaurant checkout.
    """
