# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from . import menu_additional_charge, menu_hours_interval


class Hours(BaseModel):
  """Menu availability hours."""

  model_config = ConfigDict(
    extra="allow",
  )
  intervals: list[menu_hours_interval.MenuHoursInterval] | None = None


class Menu(BaseModel):
  """A menu containing categories and fulfillment configuration."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Menu identifier.
    """
  name: str
  """
    Menu name.
    """
  category_ids: list[str] = Field(..., min_length=1)
  """
    Category identifiers included in this menu.
    """
  fulfillment_modes: list[str] | None = None
  """
    Fulfillment modes supported by this menu.
    """
  description: str | None = None
  """
    Menu description.
    """
  hours: Hours | None = None
  """
    Menu availability hours.
    """
  additional_charges: (
    list[menu_additional_charge.MenuAdditionalCharge] | None
  ) = None
  """
    Additional charges applied to orders from this menu.
    """
