# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from ...shopping.types import postal_address
from . import distance
from typing import Literal


class Location(BaseModel):
  """Filter by location using address fields and an optional radius. Partial matches are implementation-defined."""

  model_config = ConfigDict(
    extra="allow",
  )
  address: postal_address.PostalAddress | None = None
  """
    Reference address for location-based search.
    """
  radius: distance.Distance | None = None
  """
    Optional distance radius from the reference address.
    """


class MenuMerchantSearchFilters(BaseModel):
  """Filter criteria to narrow menu merchant search results. All specified filters combine with AND logic."""

  model_config = ConfigDict(
    extra="allow",
  )
  category: str | None = None
  """
    Filter by merchant category. Categories are merchant-defined strings representing merchant taxonomy.
    """
  open_now: bool | None = None
  """
    Whether the merchant is open at request time.
    """
  fulfillment_method: Literal["shipping", "pickup"] | None = None
  """
    Required fulfillment method type for the merchant.
    """
  location: Location | None = None
  """
    Filter by location using address fields and an optional radius. Partial matches are implementation-defined.
    """
