# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict
from typing import Any
from . import merchant_fulfillment_config, rich_text
from ...shopping.types import media as media_1, retail_location_resp


class Merchant(BaseModel):
  """A merchant available for discovery and restaurant ordering."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Global ID (GID) uniquely identifying this merchant.
    """
  name: str
  """
    Merchant display name.
    """
  description: rich_text.RichText | None = None
  """
    Merchant description in one or more formats. At least one format must be provided.
    """
  url: AnyUrl | None = None
  """
    Canonical merchant page URL.
    """
  category: str | None = None
  """
    Category: taxonomy path (e.g., 'Restaurants > Sushi') or merchant-defined type.
    """
  media: list[media_1.Media] | None = None
  """
    Merchant media (images, videos). First item is the featured media.
    """
  tags: list[str] | None = None
  """
    Merchant tags for categorization and search.
    """
  locations: list[retail_location_resp.RetailLocationResponse] | None = None
  """
    Merchant retail locations (stores, pickup points, etc.).
    """
  fulfillment_config: (
    merchant_fulfillment_config.RestaurantMerchantFulfillmentConfig | None
  ) = None
  """
    Merchant fulfillment capabilities and constraints for pickup and on-demand delivery.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the standard merchant model.
    """
