# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class MenuModifierSelection(BaseModel):
  """Flat modifier selection entry for a modifier group."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Selection identifier for linking nested modifier selections.
    """
  modifier_group_id: str
  """
    Modifier group identifier for this selection.
    """
  item_id: str
  """
    Selected modifier item identifier.
    """
  quantity: int | None = Field(1, ge=1)
  """
    Selected quantity for this modifier item.
    """
  parent_selection_id: str | None = None
  """
    Immediate parent selection identifier that introduced this group (for nested groups).
    """
  parent_selection_path: list[str] | None = None
  """
    Normalized path of ancestor selection identifiers from root to immediate parent.
    """
