# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from . import order_item, total_resp


class RestaurantOrderLineItem(BaseModel):
  """Order line item snapshot."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Line item identifier.
    """
  item: order_item.OrderItem
  """
    Order-time item snapshot (menu item or modifier item).
    """
  quantity: int = Field(..., ge=1)
  """
    Quantity of the item being ordered.
    """
  totals: list[total_resp.RestaurantTotalResponse]
  """
    Line item totals breakdown.
    """
  parent_id: str | None = None
  """
    Parent reference identifier for nested structures (e.g., bundles or grouped items).
    """
