# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict


class RestaurantPickupEvent(BaseModel):
  """Pickup lifecycle event payload for restaurant orders fulfilled via pickup."""

  model_config = ConfigDict(
    extra="allow",
  )
  event_id: str
  """
    Unique pickup event identifier.
    """
  event_type: Literal["ready", "arrived", "completed", "canceled"]
  """
    Pickup lifecycle event type aligned with pickup status values.
    """
  created_at: AwareDatetime
  """
    Event creation timestamp in RFC 3339 format.
    """
  description: str | None = None
  """
    Human-readable description of the pickup status.
    """
