# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, RootModel
from ..shopping.types.context import Context as Context_1
from .types import courier as courier_1, delivery_inputs_resp, quote as quote_1
from ..shopping.types import (
  message,
  pagination as pagination_1,
  price,
  retail_location_resp,
  shipping_destination_resp,
)
from ..._internal import Response_1
from typing import Literal


class DeliveryCapabilityResponse(BaseModel):
  """Standalone delivery capability for pickup and on-demand delivery."""

  model_config = ConfigDict(
    extra="allow",
  )


class Context(Context_1):
  """Location and market context for delivery operations."""

  model_config = ConfigDict(
    extra="allow",
  )


class DeliveryRequest(RootModel[delivery_inputs_resp.DeliveryInputsResponse]):
  root: delivery_inputs_resp.DeliveryInputsResponse


class DeliveryUpdateRequest(BaseModel):
  """Patchable fields for updating an existing delivery."""

  model_config = ConfigDict(
    extra="allow",
  )
  pickup: retail_location_resp.RetailLocationResponse | None = None
  """
    Updated pickup location.
    """
  dropoff: shipping_destination_resp.ShippingDestinationResponse | None = None
  """
    Updated dropoff location.
    """
  pickup_ready_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp when pickup can begin.
    """
  pickup_deadline_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp after which pickup is no longer valid.
    """
  dropoff_ready_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp when dropoff can begin.
    """
  dropoff_deadline_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp after which dropoff is no longer valid.
    """
  items_value: price.Price | None = None
  """
    Updated total value of items.
    """
  external_store_id: str | None = None
  """
    Optional store identifier for routing or pricing.
    """
  external_id: str | None = None
  """
    Optional external identifier for idempotency or correlation.
    """


class QuoteRequest(BaseModel):
  """Inputs required to request an on-demand delivery quote."""

  model_config = ConfigDict(
    extra="allow",
  )
  context: Context | None = None
  """
    Context for the quote request. Platforms MAY infer from request, but provided fields MUST override.
    """
  delivery_request: DeliveryRequest
  """
    Delivery request details used to generate a quote.
    """


class Quote(RootModel[quote_1.DeliveryQuote]):
  root: quote_1.DeliveryQuote


class QuoteResponse(BaseModel):
  """Response containing quote details and UCP metadata."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  quote: Quote
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the quote.
    """


class DeliveryListResponse(BaseModel):
  """Paginated delivery list response with UCP metadata."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  data: list[Delivery]
  """
    Deliveries matching the list query.
    """
  pagination: pagination_1.Response | None = None
  """
    Pagination information for list results.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the list results.
    """


class DeliveryResponse(BaseModel):
  """Response containing delivery details and UCP metadata."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  delivery: Delivery
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the delivery.
    """


class Delivery(BaseModel):
  """Standalone delivery resource."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique delivery identifier.
    """
  status: Literal[
    "pending",
    "pickup",
    "pickup_complete",
    "dropoff",
    "delivered",
    "canceled",
    "returned",
    "ongoing",
  ]
  """
    Delivery status.
    """
  quote_id: str | None = None
  """
    Quote identifier used to create this delivery.
    """
  delivery_request: DeliveryRequest | None = None
  """
    Original delivery request data.
    """
  tracking_url: AnyUrl | None = None
  """
    Tracking URL for delivery progress.
    """
  courier: courier_1.Courier | None = None
  """
    Assigned courier details.
    """
  courier_imminent: bool | None = None
  """
    True when the courier is imminent/near pickup.
    """
  created_at: AwareDatetime | None = None
  """
    Delivery creation timestamp.
    """
  updated_at: AwareDatetime | None = None
  """
    Delivery update timestamp.
    """
