# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel
from .types import delivery as delivery_1, delivery_request
from ..._internal import Response_1


class DeliveryRequestCapability(BaseModel):
  """Delivery request capability. Defines delivery creation and retrieval resources."""

  model_config = ConfigDict(
    extra="allow",
  )


class RequestDelivery1(BaseModel):
  """Inputs required to create a delivery from a quote."""

  model_config = ConfigDict(
    extra="allow",
  )
  quote_id: str
  """
    Associated delivery quote identifier.
    """
  external_id: str | None = None
  """
    Optional external identifier for idempotency or correlation.
    """


class DeliveryRequest(RootModel[delivery_request.DeliveryRequest]):
  root: delivery_request.DeliveryRequest


class RequestDelivery(RootModel[RequestDelivery1 | DeliveryRequest]):
  root: RequestDelivery1 | DeliveryRequest = Field(
    ..., title="Request Delivery"
  )
  """
    Inputs required to create a delivery from a quote.
    """


class Delivery(RootModel[delivery_1.Delivery]):
  root: delivery_1.Delivery


class ResponseDelivery(BaseModel):
  """Response wrapper for delivery operations."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  delivery: Delivery
  """
    Delivery details.
    """
