# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from .types import delivery_request as delivery_request_1
from ..shopping.fulfillment_update_req import Checkout as Checkout_1


class DeliveryFulfillmentExtensionUpdateRequest(BaseModel):
  """Extends shopping fulfillment with a delivery quote identifier on checkout.fulfillment."""

  model_config = ConfigDict(
    extra="allow",
  )


class Fulfillment(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  quote_id: str | None = None
  """
    Delivery quote identifier for this checkout.
    """


class Fulfillment5(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  delivery_request: delivery_request_1.DeliveryRequest | None = None
  """
    Delivery request details when no quote is provided.
    """


class Checkout(Checkout_1):
  """Checkout extended with a delivery quote identifier inside fulfillment."""

  model_config = ConfigDict(
    extra="allow",
  )
  fulfillment: Fulfillment | Fulfillment5 | None = None
