# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel
from .types import (
  delivery_location,
  delivery_quote as delivery_quote_1,
  delivery_request,
)
from ..._internal import Response_1


class DeliveryQuoteCapability(BaseModel):
  """Delivery capability with quote and delivery resources. Checkout integration is optional via a separate fulfillment extension."""

  model_config = ConfigDict(
    extra="allow",
  )


class DeliveryLocation(RootModel[delivery_location.DeliveryLocation]):
  root: delivery_location.DeliveryLocation


class DeliveryRequest(RootModel[delivery_request.DeliveryRequest]):
  root: delivery_request.DeliveryRequest


class DeliveryQuote(RootModel[delivery_quote_1.DeliveryQuote]):
  root: delivery_quote_1.DeliveryQuote


class RequestQuote(RootModel[DeliveryRequest]):
  root: DeliveryRequest


class ResponseQuote(BaseModel):
  """Response wrapper for delivery quote operations."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  delivery_quote: DeliveryQuote
  """
    Delivery quote details.
    """
