# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel
from .types import (
  context as context_1,
  merchant as merchant_1,
  merchant_search_filters,
)
from ..shopping.types import message, pagination as pagination_1
from ..._internal import Response_1


class MerchantCapability(BaseModel):
  """Merchant search and retrieval capability for menu discovery."""

  model_config = ConfigDict(
    extra="allow",
  )


class Context(RootModel[context_1.RestaurantContext]):
  root: context_1.RestaurantContext
  """
    Location and market context for merchant operations. Extends base context with 'intent' for semantic search.
    """


class SearchRequest(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  query: str
  """
    Free-text search query for merchant name.
    """
  context: Context | None = None
  filters: merchant_search_filters.MenuMerchantSearchFilters | None = None
  pagination: pagination_1.Request | None = None


class SearchResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  merchants: list[merchant_1.Merchant]
  """
    Merchants matching the search criteria.
    """
  pagination: pagination_1.Response | None = None
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the search results.
    """


class GetMerchantResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  merchant: merchant_1.Merchant | None = None
  """
    The merchant associated with the requested ID.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the requested merchant.
    """
