# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict
from typing import Literal
from .types import fulfillment_event, order_line_item
from ..._internal import ResponseOrder
from ..shopping.types import adjustment, total_resp


class PlatformConfig(BaseModel):
  """Platform's order capability configuration."""

  model_config = ConfigDict(
    extra="allow",
  )
  webhook_url: AnyUrl
  """
    URL where merchant sends order lifecycle events (webhooks).
    """


class Fulfillment(BaseModel):
  """Fulfillment lifecycle events for pickup or on-demand delivery."""

  model_config = ConfigDict(
    extra="allow",
  )
  type: Literal["pickup", "on_demand_delivery"] | None = None
  """
    Selected fulfillment type for this order.
    """
  events: list[fulfillment_event.RestaurantFulfillmentEvent] | None = None
  """
    Append-only fulfillment events aligned to the selected fulfillment type.
    """


class RestaurantOrder(BaseModel):
  """Restaurant order schema with menu modifier selections and pickup/delivery fulfillment events."""

  model_config = ConfigDict(
    extra="allow",
  )
  ucp: ResponseOrder
  id: str
  """
    Unique order identifier.
    """
  checkout_id: str
  """
    Associated checkout ID for reconciliation.
    """
  permalink_url: AnyUrl
  """
    Permalink to access the order on merchant site.
    """
  line_items: list[order_line_item.RestaurantOrderLineItem]
  """
    Immutable line items — source of truth for what was ordered.
    """
  fulfillment: Fulfillment
  """
    Fulfillment lifecycle events for pickup or on-demand delivery.
    """
  adjustments: list[adjustment.Adjustment] | None = None
  """
    Append-only event log of money movements (refunds, returns, credits, disputes, cancellations, etc.) that exist independently of fulfillment.
    """
  totals: list[total_resp.TotalResponse]
  """
    Different totals for the order.
    """
