# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict
from ...shared.types import dropoff_location_resp, pickup_location_resp
from ...shopping.types import price


class DeliveryInputsResponse(BaseModel):
  """Inputs required to create a delivery without a precomputed quote."""

  model_config = ConfigDict(
    extra="allow",
  )
  pickup: pickup_location_resp.PickupLocationResponse
  """
    Pickup location.
    """
  dropoff: dropoff_location_resp.DropoffLocationResponse
  """
    Dropoff location.
    """
  pickup_ready_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp when pickup can begin.
    """
  pickup_deadline_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp after which pickup is no longer valid.
    """
  dropoff_ready_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp when dropoff can begin.
    """
  dropoff_deadline_dt: AwareDatetime | None = None
  """
    RFC 3339 timestamp after which dropoff is no longer valid.
    """
  items_value: price.Price
  """
    Total value of items.
    """
  external_store_id: str | None = None
  """
    Optional store identifier for routing or pricing.
    """
  external_id: str | None = None
  """
    Optional external identifier for idempotency or correlation.
    """
