# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict
from ...shopping.types import price as price_1


class DeliveryQuote(BaseModel):
  """Quoted delivery price with expiration."""

  model_config = ConfigDict(
    extra="allow",
  )
  quote_id: str
  """
    Internal quote identifier.
    """
  expires_at: AwareDatetime
  """
    RFC 3339 expiration timestamp for this quote.
    """
  price: price_1.Price
  """
    Estimated delivery fee.
    """
  pickup_eta: AwareDatetime | None = None
  """
    Estimated pickup time.
    """
  dropoff_eta: AwareDatetime | None = None
  """
    Estimated dropoff time.
    """
