# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict
from . import courier as courier_1, delivery_location, tracking as tracking_1
from ...shopping.types import price as price_1


class Delivery(BaseModel):
  """Delivery object with status updates."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Delivery identifier.
    """
  quote_id: str
  """
    Associated delivery quote identifier.
    """
  status: Literal[
    "pending",
    "pickup",
    "pickup_complete",
    "dropoff",
    "delivered",
    "canceled",
    "returned",
    "failed",
  ]
  """
    Delivery status.
    """
  created_at: AwareDatetime
  """
    RFC 3339 creation timestamp.
    """
  updated_at: AwareDatetime | None = None
  """
    RFC 3339 last update timestamp.
    """
  pickup: delivery_location.DeliveryLocation | None = None
  """
    Pickup location.
    """
  dropoff: delivery_location.DeliveryLocation | None = None
  """
    Dropoff location.
    """
  price: price_1.Price | None = None
  """
    Delivery fee.
    """
  pickup_eta: AwareDatetime | None = None
  """
    Estimated pickup time.
    """
  dropoff_eta: AwareDatetime | None = None
  """
    Estimated dropoff time.
    """
  tracking: tracking_1.Tracking | None = None
  """
    Tracking details when available.
    """
  courier: courier_1.Courier | None = None
  """
    Courier details when available.
    """
