# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from .types.context import Context as Context_1
from .types import (
  message,
  pagination as pagination_1,
  product as product_1,
  search_filters,
)
from ..._internal import Response_1


class Catalog(BaseModel):
  """Product catalog search and item retrieval capability."""

  model_config = ConfigDict(
    extra="allow",
  )


class Context(Context_1):
  """Location and market context for catalog operations. Extends base context with 'intent' for semantic search."""

  model_config = ConfigDict(
    extra="allow",
  )
  intent: str | None = None
  """
    Background context for semantic search (e.g., 'looking for gift under $50', 'need something durable for outdoor use').
    """


class SearchRequest(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  query: str
  """
    Free-text search query.
    """
  context: Context | None = None
  filters: search_filters.SearchFilters | None = None
  pagination: pagination_1.Request | None = None


class SearchResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  products: list[product_1.Product]
  """
    Products matching the search criteria.
    """
  pagination: pagination_1.Response | None = None
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the search results.
    """


class GetItemResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  product: product_1.Product | None = None
  """
    The product containing the requested ID. For product ID lookups, variants may contain a representative set. For variant ID lookups, variants contains only the requested variant.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the requested item.
    """
