# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any
from pydantic import ConfigDict, Field, RootModel
from .types import applied_discount, discount_allocation, discounts_object
from .checkout_create_req import CheckoutCreateRequest


class DiscountExtensionCreateRequest(RootModel[Any]):
  root: Any = Field(..., title="Discount Extension Create Request")
  """
    Extends Checkout with discount code support, enabling agents to apply promotional, loyalty, referral, and other discount codes.
    """


class Allocation(RootModel[discount_allocation.DiscountAllocation]):
  root: discount_allocation.DiscountAllocation


class AppliedDiscount(RootModel[applied_discount.AppliedDiscount]):
  root: applied_discount.AppliedDiscount


class DiscountsObject(RootModel[discounts_object.DiscountsObject]):
  root: discounts_object.DiscountsObject


class Checkout(CheckoutCreateRequest):
  """Checkout extended with discount capability."""

  model_config = ConfigDict(
    extra="allow",
  )
  discounts: DiscountsObject | None = None
