import { z } from "zod";

// Generated by generate-env-schema.ts. Do not edit by hand.
export const BaseEnvSchema = z.object({
  FOUNDRY_IMAGE: z.string().min(1).default("ghcr.io/foundry-rs/foundry:stable"),
  SHOVEL_IMAGE: z.string().min(1).default("indexsupply/shovel:latest"),
  // --- anvil ---
  ANVIL_HOST: z.string().min(1).default("0.0.0.0"),
  ANVIL_PORT: z.coerce.number().int().default(8545),
  CHAIN_ID: z.coerce.number().int().default(31337),
  ANVIL_MNEMONIC: z.string().min(1).default("test test test test test test test test test test test junk"),
  ANVIL_BALANCE: z.coerce.number().int().default(1000000),
  ANVIL_BLOCK_TIME: z.coerce.number().int().default(1),
  ANVIL_GAS_LIMIT: z.coerce.number().int().default(30000000),
  ANVIL_DEPLOYER_KEY: z.string().min(1).default("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"),
  // --- postgres ---
  POSTGRES_USER: z.string().min(1).default("postgres"),
  POSTGRES_PASSWORD: z.string().min(1).default("postgres"),
  POSTGRES_DB: z.string().min(1).default("shovel"),
  POSTGRES_PORT: z.coerce.number().int().default(5432),
  POSTGRES_HOST: z.string().min(1).default("postgres"),
  // --- shovel ---
  ETH_RPC_URL: z.string().min(1).default("http://anvil:8545"),
  SHOVEL_START_BLOCK: z.coerce.number().int().default(0),
});

export interface BaseEnv extends z.infer<typeof BaseEnvSchema> {}
