import { z } from "zod";

// Generated by env schema generator. Do not edit by hand.
export const AppEnvSchema = z.object({
  // --- foundry ---
  FOUNDRY_IMAGE: z.string().min(1).default("ghcr.io/foundry-rs/foundry:stable"),
  // --- anvil ---
  ANVIL_HOST: z.string().min(1).default("0.0.0.0"),
  ANVIL_PORT: z.coerce.number().int().default(8545),
  CHAIN_ID: z.coerce.number().int().default(31337),
  ANVIL_MNEMONIC: z.string().min(1).default("test test test test test test test test test test test junk"),
  ANVIL_BALANCE: z.coerce.number().int().default(1000000),
  ANVIL_BLOCK_TIME: z.coerce.number().int().default(1),
  ANVIL_GAS_LIMIT: z.coerce.number().int().default(30000000),
  ANVIL_DEPLOYER_KEY: z.string().min(1).default("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"),
  DEV_MNEMONIC: z.string().min(1).default("test test test test test test test test test test test junk"),
  ESCROW_RPC_URL: z.string().min(1).default("http://127.0.0.1:8545"),
  ESCROW_OPERATOR_PRIVATE_KEY: z.string().min(1).default("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"),
  SIMULATION_SECRET: z.string().min(1).default("super-secret-sim-key"),
  SAMPLE_BASE_URL: z.string().min(1).default("http://localhost:3000"),
  PRODUCT_ID: z.string().min(1).default("bouquet_roses"),
  MIN_BUYER_ETH: z.string().min(1).default("10000000000000000"),
  AMOUNT: z.coerce.number().int().default(1000000),
  MAX_AMOUNT: z.coerce.number().int().default(1000000),
  SALT: z.coerce.number().int().default(1),
  FEE_RECEIVER: z.string().min(1).default("0x0000000000000000000000000000000000000000"),
});

export interface AppEnv extends z.infer<typeof AppEnvSchema> {}
