// Generated by `pnpm -C apps/identity-indexer generate:db-types`
// Do not edit manually; regenerate after schema changes.
type NumericString = string;

export interface IdentityEventRow {
  chain_id: NumericString;
  block_num: NumericString;
  log_idx: NumericString;
  tx_hash: Buffer;
  registry: Buffer;
  agent_id: NumericString;
  agent_uri: string | null;
  owner: Buffer | null;
}

export interface DB {
  erc8004_identity_events: IdentityEventRow;
}
