# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any
from pydantic import ConfigDict, Field, RootModel
from .types._internal_1 import MenuModifierSelection
from ..shopping.types.line_item_update_req import LineItemUpdateRequest
from ..shopping.checkout_update_req import CheckoutUpdateRequest


class CheckoutMenuModifiersExtensionUpdateRequest(RootModel[Any]):
  root: Any = Field(
    ..., title="Checkout Menu Modifiers Extension Update Request"
  )
  """
    Extends checkout with menu modifier selections for commerce ordering.
    """


class CommerceLineItem(LineItemUpdateRequest):
  """Line item extended with menu modifier selections."""

  model_config = ConfigDict(
    extra="allow",
  )
  modifier_selections: list[MenuModifierSelection] | None = None
  """
    Selected menu modifiers for this line item, including nested selections.
    """


class Checkout(CheckoutUpdateRequest):
  """Checkout extended with menu modifier selections on line items."""

  model_config = ConfigDict(
    extra="allow",
  )
  line_items: list[CommerceLineItem] | None = None
  """
    List of line items being checked out.
    """
