# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, ConfigDict, Field, RootModel
from ..shopping.types.context import Context as Context_1
from ..shopping.types import message, pagination as pagination_1
from ..._internal import Response_1
from .types import category, item as item_1, modifier_item as modifier_item_1
from .types._internal import MenuModifierGroup


class Menu(RootModel[Any]):
  root: Any = Field(..., title="Menu")
  """
    Menu discovery and configurable menu item definitions.
    """


class Context(Context_1):
  """Location and market context for menu operations. Extends base context with 'intent' for semantic search."""

  model_config = ConfigDict(
    extra="allow",
  )
  intent: str | None = None
  """
    Background context for semantic search (e.g., 'quick lunch nearby', 'family meal under $30').
    """


class SearchRequest(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  query: str
  """
    Free-text search query.
    """
  context: Context | None = None
  pagination: pagination_1.Request | None = None


class GetModifierItemResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  modifier_item: modifier_item_1.MenuModifierItem
  """
    The requested modifier item.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the requested modifier.
    """


class SearchResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  categories: list[Category]
  """
    Menu categories with nested items.
    """
  pagination: pagination_1.Response | None = None
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the search results.
    """


class GetItemResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  item: item_1.MenuItem
  """
    The requested menu item.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the requested item.
    """


class GetItemModifierGroupsResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  modifier_groups: list[MenuModifierGroup]
  """
    Modifier groups available for the item.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the requested item.
    """


class ListResponse(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  ucp: Response_1
  categories: list[Category]
  """
    Menu categories with nested items.
    """
  messages: list[message.Message] | None = None
  """
    Errors, warnings, or informational messages about the menu.
    """


class Category(RootModel[category.MenuCategory]):
  root: category.MenuCategory


class MenuItem(RootModel[item_1.MenuItem]):
  root: item_1.MenuItem


SearchResponse.model_rebuild()
ListResponse.model_rebuild()
