# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal


class LocalprotocolCommerceAuthCaptureHandlerConfig(BaseModel):
  """Configuration for the Localprotocol commerce auth/capture escrow handler."""

  model_config = ConfigDict(
    extra="allow",
  )
  chain_id: int
  """
    EVM chain ID (e.g., 8453 for Base).
    """
  escrow_contract: str
  """
    AuthCaptureEscrow contract address.
    """
  merchant_payout_address: str
  """
    Merchant payout address for captured funds.
    """
  token_collectors: list[str]
  """
    Authorization mechanisms supported by the handler.
    """
  authorization_expiry_seconds: int = Field(..., ge=1)
  """
    Authorization expiration window in seconds.
    """
  environment: Literal["sandbox", "production"] | None = None
  """
    Execution environment for the handler.
    """
