# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal
from pydantic import ConfigDict
from ...schemas.shopping.types.payment_instrument_base import (
  PaymentInstrumentBase,
)


class LocalprotocolCommerceAuthCaptureInstrument(PaymentInstrumentBase):
  """Payment instrument for Localprotocol commerce auth/capture escrow flows."""

  model_config = ConfigDict(
    extra="allow",
  )
  type: Literal["localprotocol_auth_capture"]
  """
    Indicates this is a Localprotocol commerce auth/capture instrument.
    """
  operator: str
  """
    Operator address used for the escrow authorization.
    """
  payer: str
  """
    Payer address authorizing the escrow.
    """
  receiver: str
  """
    Receiver (merchant payout) address for captured funds.
    """
  token: str
  """
    ERC-20 token contract address used for the payment.
    """
  amount: str
  """
    Amount authorized in the escrow (as a decimal string).
    """
  max_amount: str
  """
    Maximum amount allowed for the authorization (as a decimal string).
    """
  pre_approval_expiry: int
  """
    Pre-approval expiry timestamp (unix seconds).
    """
  authorization_expiry: int
  """
    Authorization expiry timestamp (unix seconds).
    """
  refund_expiry: int
  """
    Refund expiry timestamp (unix seconds).
    """
  min_fee_bps: int
  """
    Minimum fee in basis points.
    """
  max_fee_bps: int
  """
    Maximum fee in basis points.
    """
  fee_receiver: str
  """
    Fee receiver address (use zero address for none).
    """
  salt: str
  """
    Entropy to ensure unique payment hashes (as a decimal string).
    """
  token_collector: str
  """
    Token collector contract address used for authorization.
    """
  collector_data: str
  """
    Collector-specific calldata used to authorize tokens.
    """
  authorization_id: str | None = None
  """
    Authorization identifier returned by the escrow protocol.
    """
  authorize_tx_hash: str | None = None
  """
    Transaction hash for the authorization onchain.
    """
  chain_id: int | None = None
  """
    EVM chain ID where the authorization was created (optional if derived from config).
    """
  escrow_contract: str | None = None
  """
    AuthCaptureEscrow contract address (optional if derived from config).
    """
  merchant_payout_address: str | None = None
  """
    Merchant payout address used for capture.
    """
