# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal
from pydantic import ConfigDict
from ...schemas.shopping.types.payment_instrument_base import (
  PaymentInstrumentBase,
)


class LocalprotocolCommerceAuthCaptureInstrument(PaymentInstrumentBase):
  """Payment instrument for Localprotocol restaurant auth/capture escrow flows."""

  model_config = ConfigDict(
    extra="allow",
  )
  type: Literal["localprotocol_auth_capture"]
  """
    Indicates this is a Localprotocol restaurant auth/capture instrument.
    """
  authorization_id: str
  """
    Authorization identifier returned by the escrow protocol.
    """
  authorize_tx_hash: str
  """
    Transaction hash for the authorization onchain.
    """
  chain_id: int
  """
    EVM chain ID where the authorization was created.
    """
  escrow_contract: str
  """
    AuthCaptureEscrow contract address.
    """
  merchant_payout_address: str | None = None
  """
    Merchant payout address used for capture.
    """
