# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from typing import Any
from ...shopping.types import media as media_1, price as price_1
from ._internal import MenuModifierGroup


class Description(BaseModel):
  """Menu item description in one or more formats. At least one format must be provided."""

  model_config = ConfigDict(
    extra="allow",
  )
  plain: str | None = None
  """
    Plain text description.
    """
  html: str | None = None
  """
    HTML-formatted description.
    """
  markdown: str | None = None
  """
    Markdown-formatted description.
    """


class MenuItem(BaseModel):
  """A configurable menu item with modifier groups."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Menu item identifier.
    """
  name: str
  """
    Menu item name.
    """
  description: Description
  """
    Menu item description in one or more formats. At least one format must be provided.
    """
  price: price_1.Price
  """
    Base price for the menu item.
    """
  media: list[media_1.Media] | None = None
  """
    Menu item media (images, videos, 3D models).
    """
  modifier_groups: list[MenuModifierGroup] | None = None
  """
    Modifier groups available for this item.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the menu item model.
    """
