# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Interval(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  day: str
  """
    Day of week.
    """
  from_hour: int = Field(..., ge=0, le=23)
  """
    Start hour (0-23).
    """
  from_minute: int = Field(..., ge=0, le=59)
  """
    Start minute (0-59).
    """
  to_hour: int = Field(..., ge=0, le=23)
  """
    End hour (0-23).
    """
  to_minute: int = Field(..., ge=0, le=59)
  """
    End minute (0-59).
    """


class Hours(BaseModel):
  """Menu availability hours."""

  model_config = ConfigDict(
    extra="allow",
  )
  intervals: list[Interval] | None = None


class FlatCharge(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  currency_code: str | None = None
  """
    ISO 4217 currency code.
    """
  amount: float | None = None
  """
    Charge amount in major units.
    """


class PercentageCharge(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  decimal_value: float | None = Field(None, ge=0.0)
  """
    Charge percentage as a decimal.
    """


class AdditionalCharge(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  charge_type: str | None = None
  """
    Charge type identifier.
    """
  flat_charge: FlatCharge | None = None
  percentage_charge: PercentageCharge | None = None


class Menu(BaseModel):
  """A menu containing categories and fulfillment configuration."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Menu identifier.
    """
  name: str
  """
    Menu name.
    """
  category_ids: list[str] = Field(..., min_length=1)
  """
    Category identifiers included in this menu.
    """
  fulfillment_modes: list[str] | None = None
  """
    Fulfillment modes supported by this menu.
    """
  description: str | None = None
  """
    Menu description.
    """
  hours: Hours | None = None
  """
    Menu availability hours.
    """
  additional_charges: list[AdditionalCharge] | None = None
  """
    Additional charges applied to orders from this menu.
    """
