# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class MenuHoursInterval(BaseModel):
  """A single menu availability interval for a day of the week."""

  model_config = ConfigDict(
    extra="allow",
  )
  day: str
  """
    Day of week.
    """
  from_hour: int = Field(..., ge=0, le=23)
  """
    Start hour (0-23).
    """
  from_minute: int = Field(..., ge=0, le=59)
  """
    Start minute (0-59).
    """
  to_hour: int = Field(..., ge=0, le=23)
  """
    End hour (0-23).
    """
  to_minute: int = Field(..., ge=0, le=59)
  """
    End minute (0-59).
    """
