# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class FlatCharge(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  currency_code: str | None = None
  """
    ISO 4217 currency code.
    """
  amount: float | None = None
  """
    Charge amount in major units.
    """


class PercentageCharge(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  decimal_value: float | None = Field(None, ge=0.0)
  """
    Charge percentage as a decimal.
    """


class MenuAdditionalCharge(BaseModel):
  """An additional charge applied to orders from a menu."""

  model_config = ConfigDict(
    extra="allow",
  )
  charge_type: str | None = None
  """
    Charge type identifier.
    """
  flat_charge: FlatCharge | None = None
  percentage_charge: PercentageCharge | None = None
