# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, ConfigDict
from ...shopping.types import price as price_1


class MenuModifierItem(BaseModel):
  """A purchasable modifier item that can be selected within a modifier group."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Modifier item identifier.
    """
  title: str
  """
    Modifier item title.
    """
  price: price_1.Price
  """
    Price for this modifier item.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the modifier item model.
    """
